# Generated by Django 2.1.7 on 2019-07-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='lase_update_time',
            new_name='last_update_time',
        ),
    ]
